20180403

diff --git a/bin/sparky-installer b/bin/sparky-installer
--- a/bin/sparky-installer
+++ b/bin/sparky-installer
@@ -8,14 +8,14 @@
 # sparkylinux-installer has been forked
 # for SparkyLinux by pavroo <pavroo@onet.eu> 2013/08/04
 # Copyright 2013-2018 Under the GNU GPL2 License
-# Last update 2018/03/26
+# Last update 2018/04/03
 #
 # This script requires either yad or dialog to run
 
 # checking to make sure script is running with root privileges
 testroot="`whoami`"
 if [ "$testroot" != "root" ]; then
-	echo "Must be run as root...Exiting now..."
+	echo "Must be run as root... Exiting now..."
 	exit 1
 fi
 
@@ -39,10 +39,13 @@ PASSWORD="--passwordbox "
 PARTITIONPROG="cfdisk"
 TITLETEXT="Sparky (Advanced) Installer"
 
-if [ -f /usr/bin/sparky-terminal ]; then
-	SPARKYXTERM="/usr/bin/sparky-terminal"
+if [ -f /usr/bin/sparky-xterm ];then
+	SPARKYXTERM="/usr/bin/sparky-xterm"
+elif [ -f /usr/bin/sparky-terminal ];then
+	SPARKYXTERM="/usr/bin/sparky-terminal -e"
 else
-	SPARKYXTERM="x-terminal-emulator"
+	echo "sparky-xterm is missing... Exiting..."
+	exit 1
 fi
 
 if [ "$1" = "gui" -o "$2" = "gui" ]; then
@@ -67,7 +70,7 @@ if [ "$GUI" != "" ]; then
 		
 		testgparted=`which gparted`
 		if [ "$testgparted" = "" ]; then
-			PARTITIONPROG="$SPARKYXTERM -e cfdisk"
+			PARTITIONPROG="$SPARKYXTERM cfdisk"
 		else
 			PARTITIONPROG="gparted"
 		fi
@@ -107,7 +110,9 @@ fi
 if [ "$GUI" != "" ]; then
 
 DEFLANGS=`$DIALOGMENU $TITLE"$TITLETEXT" $YESNO $MENU $TEXT"Please choose the Advanced Installer language:" \
+Brazilian "Brasileiro" \
 English "English" \
+German "Deutsch" \
 Polish "Polski" \
 Exit "Exiting now..."`
 
@@ -116,8 +121,12 @@ Exit "Exiting now..."`
 		echo "$DEFLANGS" > /tmp/sparky-advanced-installer
 	fi
 
-	if [ "$DEFLANGS" = "English" ]; then
+	if [ "$DEFLANGS" = "Brazilian" ]; then
+		DEFLANG="Brazilian"
+	elif [ "$DEFLANGS" = "English" ]; then
 		DEFLANG="English"
+	elif [ "$DEFLANGS" = "German" ]; then
+		DEFLANG="German"
 	elif [ "$DEFLANGS" = "Polish" ]; then
 		DEFLANG="Polish"
 	elif [ "$DEFLANGS" = "Exit" ]; then
@@ -128,7 +137,7 @@ Exit "Exiting now..."`
 
 elif [ "$GUI" = "" ]; then
 
-	$DIALOG $TITLE"$TITLETEXT" $MENU $TEXT"Please choose the Advanced Installer language:" $HEIGHT $WIDTH $MENUHEIGHT English "English" Polish "Polski" Exit "Exiting now..." 2>/tmp/sparky-advanced-installer
+	$DIALOG $TITLE"$TITLETEXT" $MENU $TEXT"Please choose the Advanced Installer language:" $HEIGHT $WIDTH $MENUHEIGHT Brazilian "Brasileiro" English "English" German "Deutsch" Polish "Polski" Exit "Exiting now..." 2>/tmp/sparky-advanced-installer
 
 	if [ "$?" = "0" ]; then
 		DEFLANG=`cat /tmp/sparky-advanced-installer`
@@ -145,7 +154,11 @@ fi
 
 # get default's locale file
 DEFLOCDIR="/usr/share/sparky/sparky-advanced-installer"
-if [ "$DEFLANG" = "Polish" ]; then
+if [ "$DEFLANG" = "Brazilian" ]; then
+. $DEFLOCDIR/pt_BR
+elif [ "$DEFLANG" = "German" ]; then
+. $DEFLOCDIR/de
+elif [ "$DEFLANG" = "Polish" ]; then
 . $DEFLOCDIR/pl
 else
 . $DEFLOCDIR/en
@@ -606,10 +619,10 @@ GUILOG="yad"
 	$DIALOG $TITLE"$TITLETEXT" $YESNO $TEXT"$LOCAL16\n\n$LOCAL17\n\n$LOCAL18"
 	if [ $? = 0 ]; then
 
-		$SPARKYXTERM -e dpkg-reconfigure locales
-		$SPARKYXTERM -e dpkg-reconfigure console-data
+		$SPARKYXTERM "dpkg-reconfigure locales"
+		$SPARKYXTERM "dpkg-reconfigure console-data"
 		#dpkg-reconfigure -f $FRONTEND console-setup
-		$SPARKYXTERM -e dpkg-reconfigure keyboard-configuration
+		$SPARKYXTERM "dpkg-reconfigure keyboard-configuration"
 
 	fi
 
@@ -1375,8 +1388,8 @@ then
 			if [ $? = 0 ]
 			then
 				DESKTOPCHOOSE="yes"
-				$SPARKYXTERM -e apt-get update
-				$SPARKYXTERM -e apt-get install sparky-backup-desktop sparky-desktop-data -y --force-yes
+				$SPARKYXTERM "apt-get update"
+				$SPARKYXTERM "apt-get install sparky-backup-desktop sparky-desktop-data -y --force-yes"
 				/usr/bin/sparkylinux-desktop-installer gui
 			fi
 	else
@@ -1510,7 +1523,7 @@ chmod +x /tmp/Grub-Update
 
 	if [ "$GUI" != "" ]; then
 		progressbar "$LOCAL110 ... $LOCAL92 ...\n" &
-		$SPARKYXTERM -e /tmp/Grub-Update
+		$SPARKYXTERM /tmp/Grub-Update
 		sleep 1
 		rm -rf /tmp/Grub-Update
 	else
@@ -1551,7 +1564,7 @@ chmod +x /tmp/Grub-Install
 
 	if [ "$GUI" != "" ]; then
 		progressbar "$LOCAL110 ... $LOCAL92 ...\n" &
-		$SPARKYXTERM -e /tmp/Grub-Install
+		$SPARKYXTERM /tmp/Grub-Install
 		sleep 1
 		rm -rf /tmp/Grub-Install
 	else
